import { EntityID, EntityType } from "battletribes-shared/entities";
import Boulder from "./entities/Boulder";
import Cow from "./entities/Cow";
import Player from "./entities/Player";
import Tombstone from "./entities/Tombstone";
import Tree from "./entities/Tree";
import Workbench from "./entities/Workbench";
import Zombie from "./entities/Zombie";
import BerryBush from "./entities/BerryBush";
import Cactus from "./entities/Cactus";
import Yeti from "./entities/Yeti";
import IceSpikes from "./entities/IceSpikes";
import Slime from "./entities/Slime";
import Slimewisp from "./entities/Slimewisp";
import TribeTotem from "./entities/TribeTotem";
import WorkerHut from "./entities/WorkerHut";
import Barrel from "./entities/Barrel";
import Campfire from "./entities/Campfire";
import Furnace from "./entities/Furnace";
import Snowball from "./entities/Snowball";
import Krumblid from "./entities/Krumblid";
import FrozenYeti from "./entities/FrozenYeti";
import Fish from "./entities/Fish";
import ItemEntity from "./entities/ItemEntity";
import Entity from "./Entity";
import WoodenArrowProjectile from "./projectiles/WoodenArrowProjectile";
import IceShardsProjectile from "./projectiles/IceShardsProjectile";
import RockSpikeProjectile from "./projectiles/RockSpikeProjectile";
import SpearProjectile from "./projectiles/SpearProjectile";
import ResearchBench from "./entities/ResearchBench";
import WarriorHut from "./entities/WarriorHut";
import TribeWorker from "./entities/TribeWorker";
import TribeWarrior from "./entities/TribeWarrior";
import Wall from "./entities/Wall";
import SlimeSpit from "./projectiles/SlimeSpit";
import SpitPoisonArea from "./projectiles/SpitPoisonArea";
import Door from "./entities/Door";
import BattleaxeProjectile from "./projectiles/BattleaxeProjectile";
import Golem from "./entities/Golem";
import PlanterBox from "./entities/PlanterBox";
import IceArrow from "./projectiles/IceArrow";
import Pebblum from "./entities/Pebblum";
import Embrasure from "./entities/Embrasure";
import Spikes from "./entities/Spikes";
import PunjiSticks from "./entities/PunjiSticks";
import BlueprintEntity from "./entities/BlueprintEntity";
import Ballista from "./entities/Ballista";
import SlingTurret from "./entities/SlingTurret";
import Tunnel from "./entities/Tunnel";
import HealingTotem from "./entities/HealingTotem";
import Plant from "./entities/Plant";
import Fence from "./entities/Fence";
import FenceGate from "./entities/FenceGate";
import Frostshaper from "./entities/Frostshaper";
import StonecarvingTable from "./entities/StonecarvingTable";
import BallistaFrostcicle from "./projectiles/BallistaFrostcicle";
import BallistaSlimeball from "./projectiles/BallistaSlimeball";
import BallistaRock from "./projectiles/BallistaRock";
import SlingTurretRock from "./projectiles/SlingTurretRock";
import BallistaWoodenBolt from "./projectiles/BallistaWoodenBolt";
import GrassStrand from "./entities/GrassStrand";
import Decoration from "./entities/Decoration";
import Reed from "./entities/Reed";
import Lilypad from "./entities/Lilypad";
import FibrePlant from "./entities/FibrePlant";

// @Cleanup: remove this and just have entities be a collection of components
export function createEntity(entityID: EntityID, entityType: EntityType): Entity {
   switch (entityType) {
      case EntityType.cow: return new Cow(entityID);
      case EntityType.zombie: return new Zombie(entityID);
      case EntityType.tombstone: return new Tombstone(entityID);
      case EntityType.tree: return new Tree(entityID);
      case EntityType.workbench: return new Workbench(entityID);
      case EntityType.boulder: return new Boulder(entityID);
      case EntityType.berryBush: return new BerryBush(entityID);
      case EntityType.cactus: return new Cactus(entityID);
      case EntityType.yeti: return new Yeti(entityID);
      case EntityType.iceSpikes: return new IceSpikes(entityID);
      case EntityType.slime: return new Slime(entityID);
      case EntityType.slimewisp: return new Slimewisp(entityID);
      case EntityType.tribeWorker: return new TribeWorker(entityID);
      case EntityType.tribeWarrior: return new TribeWarrior(entityID);
      case EntityType.player: return new Player(entityID);
      case EntityType.tribeTotem: return new TribeTotem(entityID);
      case EntityType.workerHut: return new WorkerHut(entityID);
      case EntityType.warriorHut: return new WarriorHut(entityID);
      case EntityType.barrel: return new Barrel(entityID);
      case EntityType.campfire: return new Campfire(entityID);
      case EntityType.furnace: return new Furnace(entityID);
      case EntityType.snowball: return new Snowball(entityID);
      case EntityType.krumblid: return new Krumblid(entityID);
      case EntityType.frozenYeti: return new FrozenYeti(entityID);
      case EntityType.fish: return new Fish(entityID);
      case EntityType.itemEntity: return new ItemEntity(entityID);
      case EntityType.woodenArrow: return new WoodenArrowProjectile(entityID);
      case EntityType.ballistaWoodenBolt: return new BallistaWoodenBolt(entityID);
      case EntityType.ballistaRock: return new BallistaRock(entityID);
      case EntityType.ballistaSlimeball: return new BallistaSlimeball(entityID);
      case EntityType.ballistaFrostcicle: return new BallistaFrostcicle(entityID);
      case EntityType.slingTurretRock: return new SlingTurretRock(entityID);
      case EntityType.iceShardProjectile: return new IceShardsProjectile(entityID);
      case EntityType.rockSpikeProjectile: return new RockSpikeProjectile(entityID);
      case EntityType.spearProjectile: return new SpearProjectile(entityID);
      case EntityType.researchBench: return new ResearchBench(entityID);
      case EntityType.wall: return new Wall(entityID);
      case EntityType.slimeSpit: return new SlimeSpit(entityID);
      case EntityType.spitPoisonArea: return new SpitPoisonArea(entityID);
      case EntityType.door: return new Door(entityID);
      case EntityType.battleaxeProjectile: return new BattleaxeProjectile(entityID);
      case EntityType.golem: return new Golem(entityID);
      case EntityType.planterBox: return new PlanterBox(entityID);
      case EntityType.iceArrow: return new IceArrow(entityID);
      case EntityType.pebblum: return new Pebblum(entityID);
      case EntityType.embrasure: return new Embrasure(entityID);
      case EntityType.floorSpikes: return new Spikes(entityID, entityType);
      case EntityType.wallSpikes: return new Spikes(entityID, entityType);
      case EntityType.floorPunjiSticks: return new PunjiSticks(entityID, entityType);
      case EntityType.wallPunjiSticks: return new PunjiSticks(entityID, entityType);
      case EntityType.blueprintEntity: return new BlueprintEntity(entityID);
      case EntityType.ballista: return new Ballista(entityID);
      case EntityType.slingTurret: return new SlingTurret(entityID);
      case EntityType.tunnel: return new Tunnel(entityID);
      case EntityType.healingTotem: return new HealingTotem(entityID);
      case EntityType.plant: return new Plant(entityID);
      case EntityType.fence: return new Fence(entityID);
      case EntityType.fenceGate: return new FenceGate(entityID);
      case EntityType.frostshaper: return new Frostshaper(entityID);
      case EntityType.stonecarvingTable: return new StonecarvingTable(entityID);
      case EntityType.grassStrand: return new GrassStrand(entityID);
      case EntityType.decoration: return new Decoration(entityID);
      case EntityType.reed: return new Reed(entityID);
      case EntityType.lilypad: return new Lilypad(entityID);
      case EntityType.fibrePlant: return new FibrePlant(entityID);
      default: {
         const unreachable: never = entityType;
         return unreachable;
      }
   }
}